spring.application.name=ai-support-assistant

#spring.ai.openai.api-key =${OPENAI_API_KEY}

spring.ai.google.genai.api-key=${GEN_API_KEY}
spring.ai.google.genai.chat.model=gemini-3-flash-preview

spring.ai.google.genai.embedding.api-key=${GEN_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001

spring.datasource.url=jdbc:postgresql://localhost:5432/AI_Knowledge
spring.datasource.username=postgres
spring.datasource.password=Pranjal@12

#PG vector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=NONE